In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [14]:
df_main = pd.read_csv('anime.csv')
df_main.head()

,title,score,people_scored,popularity,members,season,title_type,studio,description,recommended,...,producers,licensors,source,genres,duration,episodes,rating,themes,demographics,favorites
0,Sousou no Frieren,9.27,869731,Popularity #104,"Members 1,411,377",Fall 2023,TV,Madhouse,During their decade-long quest to defeat the D...,819,...,"Aniplex, Dentsu, Shogakukan-Shueis...",Crunchyroll,Manga,"AdventureAdventure, Award WinningAward...",24 min. per ep.,28,PG-13 - Teens 13 or older,NaN,ShounenShounen,"88,070"
1,Steel Ball Run: JoJo no Kimyou na Bouken,9.16,86411,Popularity #1447,"Members 189,929",NaN,ONA,David Production,"In the American Old West, the world's greatest...",156,...,"Warner Bros. Japan, Studio Mausu, ...","None found, add some",Manga,"ActionAction, AdventureAdventure, ...",47 min.,Unknown,R - 17+ (violence & profanity),"HistoricalHistorical, RacingRacing","SeinenSeinen, ShounenShounen","6,051"
2,Fullmetal Alchemist: Brotherhood,9.11,2303444,Popularity #3,"Members 3,667,785",Spring 2009,TV,Bones,After a horrific alchemy experiment goes wrong...,971,...,"Aniplex, Square Enix, Mainichi Bro...","Funimation, Aniplex of America",Manga,"ActionAction, AdventureAdventure, ...",24 min. per ep.,64,R - 17+ (violence & profanity),MilitaryMilitary,ShounenShounen,"241,796"
3,Chainsaw Man Movie: Reze-hen,9.09,282353,Popularity #589,"Members 449,212",NaN,Movie,MAPPA,Despite the immediate challenges following bec...,322,...,"None found, add some","None found, add some",Manga,"ActionAction, FantasyFantasy",1 hr. 39 min.,1,R - 17+ (violence & profanity),"GoreGore, Urban FantasyUrban Fantasy",ShounenShounen,"12,951"
4,Steins;Gate,9.07,1516022,Popularity #14,"Members 2,802,086",Spring 2011,TV,White Fox,Eccentric scientist Rintarou Okabe has a never...,1075,...,"Frontier Works, Media Factory, Kad...",Funimation,Visual novel,"DramaDrama, Sci-FiSci-Fi, Susp...",24 min. per ep.,24,PG-13 - Teens 13 or older,"PsychologicalPsychological, Time Trave...",NaN,"201,780"

In [15]:
df_main.columns

Index(['title', 'score', 'people_scored', 'popularity', 'members', 'season',
       'title_type', 'studio', 'description', 'recommended', 'mixed_feelings',
       'not_recommended', 'rec', 'mix', 'not_rec', 'english_title',
       'show_type', 'status', 'aired', 'broadcast', 'producers', 'licensors',
       'source', 'genres', 'duration', 'episodes', 'rating', 'themes',
       'demographics', 'favorites'],
      dtype='str')

In [17]:
df_main.info()

<class 'pandas.DataFrame'>
RangeIndex: 10142 entries, 0 to 10141
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            10142 non-null  str
 1   score            10142 non-null  float64
 2   people_scored    10142 non-null  int64
 3   popularity       10142 non-null  str
 4   members          10142 non-null  str
 5   season           4427 non-null   str
 6   title_type       10142 non-null  str
 7   studio           9717 non-null   str
 8   description      10142 non-null  str
 9   recommended      10142 non-null  int64
 10  mixed_feelings   10142 non-null  int64
 11  not_recommended  10142 non-null  int64
 12  rec              8198 non-null   str
 13  mix              6870 non-null   str
 14  not_rec          6004 non-null   str
 15  english_title    7041 non-null   str
 16  show_type        10142 non-null  str
 17  status           10142 non-null  str
 18  aired            10142 non-null  str
 19  broadcast        4427 non-null   str
 20  producers        10142 non-null  str
 21  licensors        10142 non-null  str
 22  source           10142 non-null  str
 23  genres           9841 non-null   str
 24  duration         10142 non-null  str
 25  episodes         10142 non-null  str
 26  rating           10088 non-null  str
 27  themes           7325 non-null   str
 28  demographics     3776 non-null   str
 29  favorites        10142 non-null  str
dtypes: float64(1), int64(4), str(25)
memory usage: 2.3 MB

CLEANING

In [18]:
df = df_main.copy()

Below i took columns popularity, members, favourites and episodes and formated them to be numeric values which will aid us later in analysis

In [19]:
# 1. Clean popularity
df['popularity'] = (
    df['popularity']
    .str.replace('Popularity', '', regex=False)
    .str.replace('#', '', regex=False)
    .str.strip()
)
df['popularity'] = pd.to_numeric(df['popularity'], errors='coerce')

# 2. Clean members
df['members'] = (
    df['members']
    .str.replace('Members', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
)
df['members'] = pd.to_numeric(df['members'], errors='coerce')

# 3. Clean favorites
df['favorites'] = (
    df['favorites']
    .str.replace(',', '', regex=False)
    .str.strip()
)
df['favorites'] = pd.to_numeric(df['favorites'], errors='coerce')

# 4. Clean episodes
df['episodes'] = (
    df['episodes']
    .replace('Unknown', np.nan)
)
df['episodes'] = pd.to_numeric(df['episodes'], errors='coerce')
df.head()

,title,score,people_scored,popularity,members,season,title_type,studio,description,recommended,...,producers,licensors,source,genres,duration,episodes,rating,themes,demographics,favorites
0,Sousou no Frieren,9.27,869731,104,1411377,Fall 2023,TV,Madhouse,During their decade-long quest to defeat the D...,819,...,"Aniplex, Dentsu, Shogakukan-Shueis...",Crunchyroll,Manga,"AdventureAdventure, Award WinningAward...",24 min. per ep.,28.0,PG-13 - Teens 13 or older,NaN,ShounenShounen,88070
1,Steel Ball Run: JoJo no Kimyou na Bouken,9.16,86411,1447,189929,NaN,ONA,David Production,"In the American Old West, the world's greatest...",156,...,"Warner Bros. Japan, Studio Mausu, ...","None found, add some",Manga,"ActionAction, AdventureAdventure, ...",47 min.,NaN,R - 17+ (violence & profanity),"HistoricalHistorical, RacingRacing","SeinenSeinen, ShounenShounen",6051
2,Fullmetal Alchemist: Brotherhood,9.11,2303444,3,3667785,Spring 2009,TV,Bones,After a horrific alchemy experiment goes wrong...,971,...,"Aniplex, Square Enix, Mainichi Bro...","Funimation, Aniplex of America",Manga,"ActionAction, AdventureAdventure, ...",24 min. per ep.,64.0,R - 17+ (violence & profanity),MilitaryMilitary,ShounenShounen,241796
3,Chainsaw Man Movie: Reze-hen,9.09,282353,589,449212,NaN,Movie,MAPPA,Despite the immediate challenges following bec...,322,...,"None found, add some","None found, add some",Manga,"ActionAction, FantasyFantasy",1 hr. 39 min.,1.0,R - 17+ (violence & profanity),"GoreGore, Urban FantasyUrban Fantasy",ShounenShounen,12951
4,Steins;Gate,9.07,1516022,14,2802086,Spring 2011,TV,White Fox,Eccentric scientist Rintarou Okabe has a never...,1075,...,"Frontier Works, Media Factory, Kad...",Funimation,Visual novel,"DramaDrama, Sci-FiSci-Fi, Susp...",24 min. per ep.,24.0,PG-13 - Teens 13 or older,"PsychologicalPsychological, Time Trave...",NaN,201780

Below i converted the duration column to duration_min for the purpose of later analysis

In [20]:

def convert_duration(x):
    if pd.isna(x):
        return np.nan
    
    x = str(x).lower()
    
    if 'unknown' in x:
        return np.nan
    
    hours = 0
    minutes = 0
    
    # Extract hours
    hr_match = re.search(r'(\d+)\s*hr', x)
    if hr_match:
        hours = int(hr_match.group(1))
    
    # Extract minutes
    min_match = re.search(r'(\d+)\s*min', x)
    if min_match:
        minutes = int(min_match.group(1))
    
    total_minutes = hours * 60 + minutes
    
    return total_minutes if total_minutes > 0 else np.nan


df['duration'] = df['duration'].apply(convert_duration)
df.rename(columns={'duration': 'duration_min'}, inplace=True)

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10142 entries, 0 to 10141
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            10142 non-null  str
 1   score            10142 non-null  float64
 2   people_scored    10142 non-null  int64
 3   popularity       10142 non-null  int64
 4   members          10142 non-null  int64
 5   season           4427 non-null   str
 6   title_type       10142 non-null  str
 7   studio           9717 non-null   str
 8   description      10142 non-null  str
 9   recommended      10142 non-null  int64
 10  mixed_feelings   10142 non-null  int64
 11  not_recommended  10142 non-null  int64
 12  rec              8198 non-null   str
 13  mix              6870 non-null   str
 14  not_rec          6004 non-null   str
 15  english_title    7041 non-null   str
 16  show_type        10142 non-null  str
 17  status           10142 non-null  str
 18  aired            10142 non-null  str
 19  broadcast        4427 non-null   str
 20  producers        10142 non-null  str
 21  licensors        10142 non-null  str
 22  source           10142 non-null  str
 23  genres           9841 non-null   str
 24  duration_min     10098 non-null  float64
 25  episodes         10073 non-null  float64
 26  rating           10088 non-null  str
 27  themes           7325 non-null   str
 28  demographics     3776 non-null   str
 29  favorites        10142 non-null  int64
dtypes: float64(3), int64(7), str(20)
memory usage: 2.3 MB

In [22]:

pd.set_option('display.max_columns', None)
df.head()

,title,score,people_scored,popularity,members,season,title_type,studio,description,recommended,mixed_feelings,not_recommended,rec,mix,not_rec,english_title,show_type,status,aired,broadcast,producers,licensors,source,genres,duration_min,episodes,rating,themes,demographics,favorites
0,Sousou no Frieren,9.27,869731,104,1411377,Fall 2023,TV,Madhouse,During their decade-long quest to defeat the D...,819,144,116,I feel so catered to.\r\n\r\nIt feels like an ...,Someone recommended me to watch this title las...,Style-\r\nFrieren doesn't have its own unique ...,Frieren: Beyond Journey's End,TV,Finished Airing,"Sep 29, 2023 to Mar 22, 2024",Fridays at 23:00 (JST),"Aniplex, Dentsu, Shogakukan-Shueis...",Crunchyroll,Manga,"AdventureAdventure, Award WinningAward...",24.0,28.0,PG-13 - Teens 13 or older,NaN,ShounenShounen,88070
1,Steel Ball Run: JoJo no Kimyou na Bouken,9.16,86411,1447,189929,NaN,ONA,David Production,"In the American Old West, the world's greatest...",156,7,1,I watched the first episode and it was truly a...,I will summarize it for you in two words.\r\nN...,The part 7 adaption is similar to its previous...,Steel Ball Run: JoJo's Bizarre Adventure,ONA,Currently Airing,"Mar 19, 2026 to ?",NaN,"Warner Bros. Japan, Studio Mausu, ...","None found, add some",Manga,"ActionAction, AdventureAdventure, ...",47.0,NaN,R - 17+ (violence & profanity),"HistoricalHistorical, RacingRacing","SeinenSeinen, ShounenShounen",6051
2,Fullmetal Alchemist: Brotherhood,9.11,2303444,3,3667785,Spring 2009,TV,Bones,After a horrific alchemy experiment goes wrong...,971,69,44,"First of all, I have seen the original FMA and...",Fullmetal Alchemist: Brotherhood gets an immen...,*Spoiler Warning\r\n\r\nAside from the usual e...,Fullmetal Alchemist: Brotherhood,TV,Finished Airing,"Apr 5, 2009 to Jul 4, 2010",Sundays at 17:00 (JST),"Aniplex, Square Enix, Mainichi Bro...","Funimation, Aniplex of America",Manga,"ActionAction, AdventureAdventure, ...",24.0,64.0,R - 17+ (violence & profanity),MilitaryMilitary,ShounenShounen,241796
3,Chainsaw Man Movie: Reze-hen,9.09,282353,589,449212,NaN,Movie,MAPPA,Despite the immediate challenges following bec...,322,46,19,In short if you like and read the chainsaw man...,Quick little review because I feel my perspect...,Writing this review to compile my thoughts on ...,Chainsaw Man – The Movie: Reze Arc,Movie,Finished Airing,"Sep 19, 2025",NaN,"None found, add some","None found, add some",Manga,"ActionAction, FantasyFantasy",99.0,1.0,R - 17+ (violence & profanity),"GoreGore, Urban FantasyUrban Fantasy",ShounenShounen,12951
4,Steins;Gate,9.07,1516022,14,2802086,Spring 2011,TV,White Fox,Eccentric scientist Rintarou Okabe has a never...,1075,88,84,“No one knows what the future holds. That’s wh...,One word: Hype.\r\n\r\nBefore watching this sh...,Just a horrible anime. This is the anime equiv...,Steins;Gate,TV,Finished Airing,"Apr 6, 2011 to Sep 14, 2011",Wednesdays at 02:05 (JST),"Frontier Works, Media Factory, Kad...",Funimation,Visual novel,"DramaDrama, Sci-FiSci-Fi, Susp...",24.0,24.0,PG-13 - Teens 13 or older,"PsychologicalPsychological, Time Trave...",NaN,201780

I dropped "title_type" as its identical to our show_type column

In [23]:
df.drop(['title_type'], axis=1,inplace= True)

I took all string values in the dataframe and put them all into a consistent format

In [24]:
str_cols = df.select_dtypes(include='str').columns

df[str_cols] = df[str_cols].apply(lambda x: x.str.lower().str.strip())

From the broadcast column i engineered "broadcast_day" and "broadcast_time" so that we may be able to see trends in how different days and different hours of release affect our data

In [25]:

# Extract day
df['broadcast_day'] = df['broadcast'].str.extract(r'(\w+)', expand=False)

# Extract time
df['broadcast_time'] = df['broadcast'].str.extract(r'(\d{2}:\d{2})', expand=False)

# Convert time to datetime (time format)
df['broadcast_time'] = pd.to_datetime(
    df['broadcast'].str.extract(r'(\d{2}:\d{2})')[0],
    format='%H:%M',
    errors='coerce'
).dt.time

In [26]:
df['demographics'].value_counts()

demographics
shounenshounen                          1806
seinenseinen                             887
kidskids                                 532
shoujoshoujo                             389
joseijosei                               114
kidskids,         shounenshounen          46
seinenseinen,         shounenshounen       1
kidskids,         shoujoshoujo             1
Name: count, dtype: int64

columns like genres and themes have repeating string values in the same cell, this was handled below

In [27]:

def fix_joined_repeat(text):
    if pd.isna(text):
        return np.nan
    
    parts = [p.strip() for p in str(text).split(',')]
    cleaned_parts = []
    
    for part in parts:
        if len(part) % 2 == 0 and part[:len(part)//2] == part[len(part)//2:]:
            cleaned_parts.append(part[:len(part)//2])
        else:
            cleaned_parts.append(part)
    
    return ', '.join(cleaned_parts)

df['demographics'] = df['demographics'].apply(fix_joined_repeat)
df['genres'] = df['genres'].apply(fix_joined_repeat)
df['themes'] = df['themes'].apply(fix_joined_repeat)

In [28]:
df['genres'].value_counts()

genres
comedy                                    937
action, adventure, fantasy                478
slice of life                             301
comedy, romance                           293
sci-fi                                    269
                                         ...
action, comedy, mystery, sci-fi, ecchi      1
avant garde, horror, suspense               1
action, horror                              1
action, fantasy, gourmet                    1
comedy, romance, sci-fi, supernatural       1
Name: count, Length: 672, dtype: int64

In [29]:
df.head()

,title,score,people_scored,popularity,members,season,studio,description,recommended,mixed_feelings,not_recommended,rec,mix,not_rec,english_title,show_type,status,aired,broadcast,producers,licensors,source,genres,duration_min,episodes,rating,themes,demographics,favorites,broadcast_day,broadcast_time
0,sousou no frieren,9.27,869731,104,1411377,fall 2023,madhouse,during their decade-long quest to defeat the d...,819,144,116,i feel so catered to.\r\n\r\nit feels like an ...,someone recommended me to watch this title las...,style-\r\nfrieren doesn't have its own unique ...,frieren: beyond journey's end,tv,finished airing,"sep 29, 2023 to mar 22, 2024",fridays at 23:00 (jst),"aniplex, dentsu, shogakukan-shueis...",crunchyroll,manga,"adventure, award winning, drama, fantasy",24.0,28.0,pg-13 - teens 13 or older,NaN,shounen,88070,fridays,23:00:00
1,steel ball run: jojo no kimyou na bouken,9.16,86411,1447,189929,NaN,david production,"in the american old west, the world's greatest...",156,7,1,i watched the first episode and it was truly a...,i will summarize it for you in two words.\r\nn...,the part 7 adaption is similar to its previous...,steel ball run: jojo's bizarre adventure,ona,currently airing,"mar 19, 2026 to ?",NaN,"warner bros. japan, studio mausu, ...","none found, add some",manga,"action, adventure, mystery, supernatural",47.0,NaN,r - 17+ (violence & profanity),"historical, racing","seinen, shounen",6051,NaN,NaT
2,fullmetal alchemist: brotherhood,9.11,2303444,3,3667785,spring 2009,bones,after a horrific alchemy experiment goes wrong...,971,69,44,"first of all, i have seen the original fma and...",fullmetal alchemist: brotherhood gets an immen...,*spoiler warning\r\n\r\naside from the usual e...,fullmetal alchemist: brotherhood,tv,finished airing,"apr 5, 2009 to jul 4, 2010",sundays at 17:00 (jst),"aniplex, square enix, mainichi bro...","funimation, aniplex of america",manga,"action, adventure, drama, fantasy",24.0,64.0,r - 17+ (violence & profanity),military,shounen,241796,sundays,17:00:00
3,chainsaw man movie: reze-hen,9.09,282353,589,449212,NaN,mappa,despite the immediate challenges following bec...,322,46,19,in short if you like and read the chainsaw man...,quick little review because i feel my perspect...,writing this review to compile my thoughts on ...,chainsaw man – the movie: reze arc,movie,finished airing,"sep 19, 2025",NaN,"none found, add some","none found, add some",manga,"action, fantasy",99.0,1.0,r - 17+ (violence & profanity),"gore, urban fantasy",shounen,12951,NaN,NaT
4,steins;gate,9.07,1516022,14,2802086,spring 2011,white fox,eccentric scientist rintarou okabe has a never...,1075,88,84,“no one knows what the future holds. that’s wh...,one word: hype.\r\n\r\nbefore watching this sh...,just a horrible anime. this is the anime equiv...,steins;gate,tv,finished airing,"apr 6, 2011 to sep 14, 2011",wednesdays at 02:05 (jst),"frontier works, media factory, kad...",funimation,visual novel,"drama, sci-fi, suspense",24.0,24.0,pg-13 - teens 13 or older,"psychological, time travel",NaN,201780,wednesdays,02:05:00

ensuring all "unknown" values in our data are replaced with null value, and light formating of broadcast_day

In [30]:
for i in str_cols:
    df[i] = df[i].replace({
    'unknown': np.nan,
    'not': np.nan,
    'none found, add some': np.nan
})

df['broadcast_day'] = (
    df['broadcast_day']
    .str.replace('s$', '', regex=True)   # remove 's' at end
    .str.capitalize()
)

days_order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

df['broadcast_day'] = pd.Categorical(
    df['broadcast_day'],
    categories=days_order,
    ordered=True
)

C:\Users\vince\AppData\Local\Temp\ipykernel_10412\3171798173.py:16: Pandas4Warning: Constructing a Categorical with a dtype and values containing non-null entries not in that dtype's categories is deprecated and will raise in a future version.
  df['broadcast_day'] = pd.Categorical(

In [31]:
df['broadcast_day'].value_counts().sort_index()

broadcast_day
Monday       366
Tuesday      428
Wednesday    387
Thursday     441
Friday       605
Saturday     706
Sunday       769
Name: count, dtype: int64

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10142 entries, 0 to 10141
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            10142 non-null  str
 1   score            10142 non-null  float64
 2   people_scored    10142 non-null  int64
 3   popularity       10142 non-null  int64
 4   members          10142 non-null  int64
 5   season           4427 non-null   str
 6   studio           9717 non-null   str
 7   description      10142 non-null  str
 8   recommended      10142 non-null  int64
 9   mixed_feelings   10142 non-null  int64
 10  not_recommended  10142 non-null  int64
 11  rec              8198 non-null   str
 12  mix              6870 non-null   str
 13  not_rec          6004 non-null   str
 14  english_title    7041 non-null   str
 15  show_type        10142 non-null  str
 16  status           10142 non-null  str
 17  aired            10142 non-null  str
 18  broadcast        3744 non-null   str
 19  producers        7310 non-null   str
 20  licensors        4175 non-null   str
 21  source           9724 non-null   str
 22  genres           9841 non-null   str
 23  duration_min     10098 non-null  float64
 24  episodes         10073 non-null  float64
 25  rating           10088 non-null  str
 26  themes           7325 non-null   str
 27  demographics     3776 non-null   str
 28  favorites        10142 non-null  int64
 29  broadcast_day    3702 non-null   category
 30  broadcast_time   3675 non-null   object
dtypes: category(1), float64(3), int64(7), object(1), str(19)
memory usage: 2.3+ MB

In [33]:
df.head()

,title,score,people_scored,popularity,members,season,studio,description,recommended,mixed_feelings,not_recommended,rec,mix,not_rec,english_title,show_type,status,aired,broadcast,producers,licensors,source,genres,duration_min,episodes,rating,themes,demographics,favorites,broadcast_day,broadcast_time
0,sousou no frieren,9.27,869731,104,1411377,fall 2023,madhouse,during their decade-long quest to defeat the d...,819,144,116,i feel so catered to.\r\n\r\nit feels like an ...,someone recommended me to watch this title las...,style-\r\nfrieren doesn't have its own unique ...,frieren: beyond journey's end,tv,finished airing,"sep 29, 2023 to mar 22, 2024",fridays at 23:00 (jst),"aniplex, dentsu, shogakukan-shueis...",crunchyroll,manga,"adventure, award winning, drama, fantasy",24.0,28.0,pg-13 - teens 13 or older,NaN,shounen,88070,Friday,23:00:00
1,steel ball run: jojo no kimyou na bouken,9.16,86411,1447,189929,NaN,david production,"in the american old west, the world's greatest...",156,7,1,i watched the first episode and it was truly a...,i will summarize it for you in two words.\r\nn...,the part 7 adaption is similar to its previous...,steel ball run: jojo's bizarre adventure,ona,currently airing,"mar 19, 2026 to ?",NaN,"warner bros. japan, studio mausu, ...",NaN,manga,"action, adventure, mystery, supernatural",47.0,NaN,r - 17+ (violence & profanity),"historical, racing","seinen, shounen",6051,NaN,NaT
2,fullmetal alchemist: brotherhood,9.11,2303444,3,3667785,spring 2009,bones,after a horrific alchemy experiment goes wrong...,971,69,44,"first of all, i have seen the original fma and...",fullmetal alchemist: brotherhood gets an immen...,*spoiler warning\r\n\r\naside from the usual e...,fullmetal alchemist: brotherhood,tv,finished airing,"apr 5, 2009 to jul 4, 2010",sundays at 17:00 (jst),"aniplex, square enix, mainichi bro...","funimation, aniplex of america",manga,"action, adventure, drama, fantasy",24.0,64.0,r - 17+ (violence & profanity),military,shounen,241796,Sunday,17:00:00
3,chainsaw man movie: reze-hen,9.09,282353,589,449212,NaN,mappa,despite the immediate challenges following bec...,322,46,19,in short if you like and read the chainsaw man...,quick little review because i feel my perspect...,writing this review to compile my thoughts on ...,chainsaw man – the movie: reze arc,movie,finished airing,"sep 19, 2025",NaN,NaN,NaN,manga,"action, fantasy",99.0,1.0,r - 17+ (violence & profanity),"gore, urban fantasy",shounen,12951,NaN,NaT
4,steins;gate,9.07,1516022,14,2802086,spring 2011,white fox,eccentric scientist rintarou okabe has a never...,1075,88,84,“no one knows what the future holds. that’s wh...,one word: hype.\r\n\r\nbefore watching this sh...,just a horrible anime. this is the anime equiv...,steins;gate,tv,finished airing,"apr 6, 2011 to sep 14, 2011",wednesdays at 02:05 (jst),"frontier works, media factory, kad...",funimation,visual novel,"drama, sci-fi, suspense",24.0,24.0,pg-13 - teens 13 or older,"psychological, time travel",NaN,201780,Wednesday,02:05:00

In [41]:
df.to_csv("cleaned_anime.csv", index=False)